import type { Metadata } from "next";
import { Source_Code_Pro } from "next/font/google";
import "./globals.css";

// フォントの設定
const sourceCodePro = Source_Code_Pro({
  subsets: ["latin"],
  display: "swap",
});
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${sourceCodePro.className} antialiased`}>{children}</body>
    </html>
  );
}
