"use client";

// biome-ignore assist/source/organizeImports: <AUTO-GENERATED>
import { type SyntheticEvent, useMemo, useState } from "react";
import DatePicker, { registerLocale } from "react-datepicker";
import { ja } from "date-fns/locale/ja";
import { EtaxModal } from "@/components/medical/EtaxModal";
import { MedicalForm } from "@/components/medical/MedicalForm";
import { TrashModal } from "@/components/medical/TrashModal";
import { UndoToast } from "@/components/medical/UndoToast";
import { useMedicalData } from "@/hooks/useMedicalData";
import type { FurusatoRecord, MedicalCategory, MedicalRecord } from "@/types/tax";
import { SuggestInput } from "../components/SuggestInput";
import { TaxCard } from "../components/TaxCard";
import { TaxForm, TaxLabel } from "../components/TaxForm";
import { TaxTable } from "../components/TaxTable";
import { register } from "module";

registerLocale("ja", ja); // これでDatePickerが日本語になります

// e-Taxの4区分を判定して表示するパーツ
const ETagCategoryChecks = ({ usedCategories }: { usedCategories: Set<string> }) => {
  const categories = [
    { label: "診", id: "診療・治療" },
    { label: "薬", id: "医薬品購入" },
    { label: "介", id: "介護サービス" },
    { label: "他", id: "その他の医療費（交通費など）" },
  ];

  return (
    <div className="flex gap-1 mt-2">
      {categories.map((cat) => {
        const isActive = usedCategories.has(cat.id);
        return (
          <div
            key={cat.id}
            className={`text-[9px] w-5 h-5 flex items-center justify-center rounded border font-bold ${
              isActive
                ? "bg-blue-600 border-blue-600 text-white"
                : "bg-transparent border-slate-300 text-slate-300 dark:border-slate-600 dark:text-slate-600"
            }`}
            title={cat.id} // ホバー時にフルネーム表示
          >
            {isActive ? "✓" : ""}
            <span className={isActive ? "hidden" : "block"}>{cat.label}</span>
          </div>
        );
      })}
    </div>
  );
};

export default function TaxBuddyPage() {
  // --- 1. Hooksからデータと操作を取得 ---
  const {
    records,
    deletedRecords,
    history,
    isLoading,
    upsertRecord,
    updateCitiesHistory,
    deleteRecord,
    restoreRecord,
    clearTrash,
    exportToCsv,
    importFromCsv,
    sortOrder,
    toggleSort,
  } = useMedicalData();

  // --- 2. ページ固有のUI状態管理のみ残す ---
  const [formData, setFormData] = useState<Omit<MedicalRecord, "id">>({
    date: new Date().toISOString().split("T")[0],
    patientName: "",
    providerName: "",
    category: "診療代",
    amount: 0,
    reimbursement: 0,
  });
  const [editingId, setEditingId] = useState<string | null>(null);
  const [showEtaxModal, setShowEtaxModal] = useState(false);
  const [showTrashModal, setShowTrashModal] = useState(false);
  const [showUndo, setShowUndo] = useState(false);
  const [lastDeleted, setLastDeleted] = useState<MedicalRecord | null>(null);
  const [activeTab, setActiveTab] = useState<"medical" | "furusato">("medical");
  const [furusatoRecords, setFurusatoRecords] = useState<FurusatoRecord[]>([]);
  const [furusatoForm, setFurusatoForm] = useState<Omit<FurusatoRecord, "id">>({
    date: new Date().toISOString().split("T")[0],
    city: "",
    amount: 0,
    memo: "",
    isOneStop: false,
    isReceived: false,
  });

  // 3. 計算ロジック (useMemo)
  // etaxSummary: e-Tax用の区分チェックに使うデータ
  const etaxSummary = useMemo(() => {
    const summaryMap: Record<string, any> = {};
    records.forEach((r) => {
      const key = `${r.patientName}-${r.providerName}`;
      if (!summaryMap[key]) {
        summaryMap[key] = {
          patientName: r.patientName,
          providerName: r.providerName,
          totalAmount: 0,
          totalReimbursement: 0,
          usedCategories: new Set<string>(),
        };
      }
      summaryMap[key].usedCategories.add(r.category);
      summaryMap[key].totalAmount += r.amount;
      summaryMap[key].totalReimbursement += r.reimbursement;
    });
    return Object.values(summaryMap);
  }, [records]);

  // stats: 合計金額、医療費控除額、ふるさと納税合計、還付見込額など
  const stats = useMemo(() => {
    const total = records.reduce((sum, r) => sum + r.amount, 0);
    const totalReimbursement = records.reduce((sum, r) => sum + r.reimbursement, 0);
    const netExpense = total - totalReimbursement;
    const medicalDeduction = Math.max(0, netExpense - 100000);
    const furusatoTotal = furusatoRecords.reduce((sum, r) => sum + r.amount, 0);
    const estimatedRefund = Math.floor(medicalDeduction * 0.2) + Math.max(0, furusatoTotal - 2000);

    return { total, netExpense, medicalDeduction, furusatoTotal, estimatedRefund };
  }, [records, furusatoRecords]);

  // --- 3. ハンドラー関数の整理 ---
  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const id = editingId || crypto.randomUUID();

    // upsertRecord を実行
    await upsertRecord({
      ...formData,
      id,
      // 確実に型を合わせるためのスプレッド
    } as MedicalRecord);

    // フォームのリセット
    setEditingId(null);
    setFormData({
      ...formData,
      patientName: formData.patientName, // 名前は残す（連続入力のため）
      providerName: formData.providerName, // 場所も残す
      amount: 0,
      reimbursement: 0,
    });
  };

  const handleDelete = async (id: string) => {
    const deleted = await deleteRecord(id);
    if (deleted) {
      setLastDeleted(deleted);
      setShowUndo(true);
      setTimeout(() => setShowUndo(false), 5000);
    }
  };

  // if (isLoading) return <div className="p-8 text-center font-black">Loading...</div>;

  // レコード編集開始処理（医療費）
  const startEdit = (record: MedicalRecord) => {
    console.log("startEditが実行されました:", record.id);

    // 1. 編集モードに切り替え
    setEditingId(record.id);

    // 2. フォームにデータを流し込む
    setFormData({
      date: record.date,
      patientName: record.patientName,
      providerName: record.providerName,
      category: record.category,
      amount: record.amount,
      reimbursement: record.reimbursement,
    });

    console.log("Stateの更新を指示しました");

    // 3. スクロール（念のためsetTimeoutで少し遅らせる）
    const formElement = document.querySelector("form");
    if (formElement) {
      formElement.scrollIntoView({ behavior: "smooth", block: "start" });
    }
  };
  // const startEdit = (record: MedicalRecord) => {
  //   setEditingId(record.id);
  //   setFormData({
  //     date: record.date,
  //     patientName: record.patientName,
  //     providerName: record.providerName,
  //     category: record.category,
  //     amount: record.amount,
  //     reimbursement: record.reimbursement,
  //   });
  //   // フォームまでスクロールさせる
  //   window.scrollTo({ top: 0, behavior: "smooth" });
  // };

  // 6. フォーム送信処理 (ふるさと納税)
  const handleFurusatoSubmit = (e: SyntheticEvent<HTMLFormElement>) => {
    e.preventDefault();
    const newRecord: FurusatoRecord = { ...furusatoForm, id: crypto.randomUUID() };
    // レコードの更新
    setFurusatoRecords([newRecord, ...furusatoRecords]);

    // ★修正：setHistory ではなく Hooks の関数を呼ぶ
    if (furusatoForm.city) {
      updateCitiesHistory(furusatoForm.city); // これでエラーが消えます！
    }
    setFurusatoForm({ ...furusatoForm, city: "", amount: 0, memo: "" });
  };

  const toggleFurusatoReceived = (id: string) => {
    setFurusatoRecords(
      furusatoRecords.map((r) => (r.id === id ? { ...r, isReceived: !r.isReceived } : r)),
    );
  };

  // データの読み込み中は真っ白（またはローディング表示）にする
  if (isLoading) {
    return <div className="min-h-screen bg-white dark:bg-slate-900" />;
  }

  <div className="fixed top-0 left-0 bg-black text-white z-[9999]">
    現在の名前: {formData.patientName}
  </div>;

  return (
    <main className="h-screen flex flex-col overflow-hidden p-8 max-w-5xl mx-auto font-sans min-h-screen transition-colors duration-300 bg-white dark:bg-slate-900 text-slate-900 dark:text-slate-100">
      <div className="flex justify-between items-center mb-8 flex-none">
        <h1 className="text-3xl font-bold text-center text-blue-600 dark:text-blue-400">
          TaxBuddy 🩺🎁
        </h1>
        <div className="flex gap-2">
          {/* インポートボタン（見た目は普通のボタンですが、中身はファイル選択） */}
          <label className="bg-amber-600 text-white px-4 py-2 rounded-md hover:bg-amber-700 transition flex items-center gap-2 text-sm font-bold cursor-pointer">
            📥 CSVを取り込む
            <input type="file" accept=".csv" className="hidden" onChange={importFromCsv} />
          </label>

          <button
            type="button"
            onClick={exportToCsv}
            className="bg-green-600 text-white px-4 py-2 rounded-md hover:bg-green-700 transition flex items-center gap-2 text-sm font-bold"
          >
            📊 Numbers形式で書き出す
          </button>
        </div>
      </div>

      <div className="flex flex-none p-1 bg-slate-100 dark:bg-slate-800 rounded-xl mb-6 w-full max-w-md mx-auto shadow-inner">
        <button
          type="button"
          onClick={() => setActiveTab("medical")}
          className={`flex-1 flex items-center justify-center gap-2 py-2 text-sm font-bold rounded-lg transition-all ${activeTab === "medical" ? "bg-white dark:bg-slate-700 shadow-sm text-blue-600 dark:text-blue-400" : "text-slate-500 hover:text-slate-700 dark:hover:text-slate-300"}`}
        >
          🩺 医療費控除
        </button>
        <button
          type="button"
          onClick={() => setActiveTab("furusato")}
          className={`flex-1 flex items-center justify-center gap-2 py-2 text-sm font-bold rounded-lg transition-all ${activeTab === "furusato" ? "bg-white dark:bg-slate-700 shadow-sm text-pink-600 dark:text-pink-400" : "text-slate-500 hover:text-slate-700 dark:hover:text-slate-300"}`}
        >
          🎁 ふるさと納税
        </button>
      </div>

      <div className="flex-none grid grid-cols-1 md:grid-cols-4 gap-4 mb-8 text-right">
        <TaxCard label="実質負担額 (医療費)" amount={stats.netExpense} color="slate" />
        <TaxCard label="医療費控除額 (概算)" amount={stats.medicalDeduction} color="blue" />
        <TaxCard label="ふるさと納税合計" amount={stats.furusatoTotal} color="pink" />
        <TaxCard label="還付・減税見込額" amount={stats.estimatedRefund} color="green" />
      </div>

      {activeTab === "medical" && (
        <div className="animate-in fade-in duration-300 flex-1 flex flex-col overflow-y-auto pr-2 custom-scrollbar">
          <TaxForm
            onSubmit={handleSubmit}
            color={editingId ? "orange" : "blue"} // 編集時は色を変えると分かりやすい
            buttonText={editingId ? "修正を保存する" : "医療費を追加"}
          >
            <div className="flex flex-col gap-1">
              <TaxLabel>受診日</TaxLabel>
              <DatePicker
                selected={formData.date ? new Date(formData.date) : null}
                onChange={(date: Date | null) => {
                  if (date) {
                    const yyyy = date.getFullYear();
                    const mm = String(date.getMonth() + 1).padStart(2, "0");
                    const dd = String(date.getDate()).padStart(2, "0");
                    setFormData({ ...formData, date: `${yyyy}-${mm}-${dd}` });
                  }
                }}
                locale="ja"
                dateFormat="yyyy/MM/dd"
                className="p-3 text-lg border-2 rounded-xl font-bold w-full h-[52px] dark:bg-slate-700 dark:border-slate-600 outline-none focus:ring-4 focus:ring-blue-500/20 cursor-pointer"
              />
            </div>
            <div className="flex flex-col gap-1">
              <TaxLabel>氏名</TaxLabel>
              <input
                type="text"
                placeholder="氏名"
                className="h-[52px] p-2 border rounded-md dark:bg-slate-700 dark:text-white dark:border-slate-600"
                value={formData.patientName}
                onChange={(e) => setFormData({ ...formData, patientName: e.target.value })}
                required
              />
            </div>
            <div className="flex flex-col gap-1">
              <TaxLabel>病院・薬局</TaxLabel>
              <SuggestInput
                placeholder="病院・薬局名"
                value={formData.providerName}
                onChange={(val) => setFormData({ ...formData, providerName: val })}
                suggestions={history.providerNames}
                className="h-[52px]"
                required
              />
            </div>
            <div className="flex flex-col gap-1">
              <TaxLabel>区分</TaxLabel>
              <select
                className="h-[52px] p-2 border-2 rounded-xl dark:bg-slate-700 dark:text-white dark:border-slate-600"
                value={formData.category}
                onChange={(e) =>
                  setFormData({ ...formData, category: e.target.value as MedicalCategory })
                }
              >
                <option value="診療・治療">診療・治療</option>
                <option value="医薬品購入">医薬品購入</option>
                <option value="介護サービス">介護サービス</option>
                <option value="その他の医療費（交通費など）">その他の医療費（交通費など）</option>
              </select>
            </div>
            <div className="flex flex-col gap-1">
              <TaxLabel>金額</TaxLabel>
              <input
                type="number"
                placeholder="金額"
                className="h-[52px] p-2 border rounded-md dark:bg-slate-700 text-right"
                value={formData.amount || ""}
                onChange={(e) => setFormData({ ...formData, amount: Number(e.target.value) })}
                required
              />
            </div>
            {/* 金額入力の次に追加 */}
            <div className="flex flex-col gap-1">
              <TaxLabel>補填金額</TaxLabel>
              <input
                type="number"
                placeholder="保険金など"
                className="h-[52px] p-2 border rounded-md dark:bg-slate-700 text-right text-pink-500 font-bold"
                value={formData.reimbursement || ""}
                onChange={(e) =>
                  setFormData({ ...formData, reimbursement: Number(e.target.value) })
                }
              />
              <p className="text-[10px] text-slate-400">※保険金や高額療養費で戻る額</p>
            </div>
            {/* 編集中のときだけ「キャンセル」ボタンを出す（お好みで） */}
            {editingId && (
              <button
                type="button"
                onClick={() => {
                  setEditingId(null);
                  setFormData({ ...formData, providerName: "", amount: 0, reimbursement: 0 });
                }}
                className="mt-2 text-xs text-slate-500 underline"
              >
                編集をキャンセル
              </button>
            )}
          </TaxForm>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 mt-8 pb-20">
            <div className="lg:col-span-2 flex flex-col gap-4">
              <h3 className="font-bold flex items-center gap-2 text-blue-600">📋 入力明細</h3>
              <button
                type="button"
                onClick={() => setShowTrashModal(true)}
                className="text-xs font-bold text-slate-400 hover:text-slate-600 flex items-center gap-1"
              >
                🗑️ ゴミ箱 ({deletedRecords.length})
              </button>
              <TaxTable
                headers={["日付", "氏名", "場所", "金額"]}
                color="blue"
                rows={records.map((r) => ({
                  id: r.id,
                  cells: [r.date, r.patientName, r.providerName, `¥${r.amount.toLocaleString()}`],
                }))}
                onDelete={handleDelete}
                onEdit={(id) => {
                  // ← これを TaxTable に渡せるようにします
                  const record = records.find((r) => r.id === id);
                  console.log("見つかったデータ：", record);
                  if (record) startEdit(record);
                  else {
                    console.warn("編集対象のデータが見つかりません:ID:", id);
                  }
                }}
                emptyMessage="医療費のデータがありません"
                sortOrder={sortOrder}
                onSort={() => toggleSort("medical")}
              />
            </div>

            <div className="flex flex-col gap-4">
              <div className="p-6 bg-slate-50 dark:bg-slate-800/50 rounded-2xl border-2 border-dashed border-slate-200 dark:border-slate-700">
                <h3 className="text-sm font-bold text-slate-700 dark:text-slate-200 flex items-center gap-2 mb-4">
                  <span className="bg-blue-500 text-white text-[10px] py-0.5 px-2 rounded font-black">
                    e-Tax用
                  </span>
                  病院別の合計
                </h3>

                {/* ↓ここが追加する拡大ボタンです */}
                <button
                  type="button"
                  onClick={() => setShowEtaxModal(true)}
                  className="flex items-center gap-1 text-[10px] bg-white dark:bg-slate-700 border border-slate-200 dark:border-slate-600 px-2 py-1.5 rounded-lg shadow-sm hover:shadow-md hover:translate-y-[-1px] transition-all font-black text-blue-600 dark:text-blue-400 hover: cursor-pointer mb-4"
                >
                  🔍 全画面で大きく表示
                </button>

                {etaxSummary.length > 0 ? (
                  <div className="flex flex-col gap-2">
                    {etaxSummary.map((s) => (
                      <div
                        key={`${s.patientName}-${s.providerName}`}
                        className="bg-white dark:bg-slate-800 p-4 rounded-xl border border-slate-200 dark:border-slate-700 flex flex-col gap-3 shadow-sm min-h-[100px]"
                      >
                        {/* 上段：名前と金額のエリア */}
                        <div className="flex justify-between items-start gap-2">
                          {/* 左側：受診者と病院名（幅を確保して折り返しを防ぐ） */}
                          <div className="flex flex-col min-w-0 flex-1">
                            <span className="text-[11px] text-slate-400 font-black leading-tight mb-1">
                              {s.patientName}
                            </span>
                            <span className="text-base font-black truncate leading-tight dark:text-slate-100">
                              {s.providerName}
                            </span>
                          </div>

                          {/* 右側：金額（右寄せを固定） */}
                          <div className="flex flex-col items-end shrink-0 ml-2">
                            <span className="text-blue-600 dark:text-blue-400 font-mono font-black text-lg leading-none">
                              ¥{s.totalAmount.toLocaleString()}
                            </span>
                            {s.totalReimbursement > 0 && (
                              <span className="text-pink-600 dark:text-pink-400 font-mono font-black text-base mt-1 leading-none">
                                ▲ ¥{s.totalReimbursement.toLocaleString()}
                              </span>
                            )}
                          </div>
                        </div>

                        {/* 下段：区分チェック（線を引いて独立させる） */}
                        <div className="pt-2 border-t border-slate-100 dark:border-slate-700">
                          <ETagCategoryChecks usedCategories={s.usedCategories} />
                        </div>
                      </div>
                    ))}
                  </div>
                ) : (
                  <p className="text-center text-xs text-slate-400">データなし</p>
                )}
              </div>
            </div>
          </div>
        </div>
      )}

      {activeTab === "furusato" && (
        <div className="animate-in fade-in duration-300 flex-1 flex flex-col overflow-y-auto pr-2 custom-scrollbar">
          <TaxForm onSubmit={handleFurusatoSubmit} color="pink" buttonText="寄付を追加">
            <div className="flex flex-col gap-1">
              <TaxLabel>寄付日</TaxLabel>
              <DatePicker
                selected={furusatoForm.date ? new Date(furusatoForm.date) : null}
                onChange={(date: Date | null) => {
                  if (date)
                    setFurusatoForm({ ...furusatoForm, date: date.toISOString().split("T")[0] });
                }}
                locale="ja"
                dateFormat="yyyy/MM/dd"
                className="p-3 text-lg border-2 rounded-xl font-bold w-full dark:bg-slate-700 dark:border-slate-600 outline-none focus:ring-4 focus:ring-pink-500/20 cursor-pointer"
              />
            </div>
            <div className="flex flex-col gap-1">
              <TaxLabel>自治体名</TaxLabel>
              <SuggestInput
                placeholder="寄付先の自治体名"
                value={furusatoForm.city}
                onChange={(val) => setFurusatoForm({ ...furusatoForm, city: val })}
                suggestions={history.cities}
                className="h-[52px]"
                required
              />
            </div>
            <div className="flex flex-col gap-1">
              <TaxLabel>金額</TaxLabel>
              <input
                type="number"
                placeholder="金額"
                className="h-[52px] p-2 border rounded-md dark:bg-slate-700"
                value={furusatoForm.amount || ""}
                onChange={(e) =>
                  setFurusatoForm({ ...furusatoForm, amount: Number(e.target.value) })
                }
                required
              />
            </div>
            <div className="flex flex-col gap-1">
              <TaxLabel>返礼品のメモ</TaxLabel>
              <input
                type="text"
                placeholder="返礼品のメモ"
                className="h-[52px] p-2 border rounded-md dark:bg-slate-700"
                value={furusatoForm.memo}
                onChange={(e) => setFurusatoForm({ ...furusatoForm, memo: e.target.value })}
              />
            </div>
            <div className="flex flex-col gap-1">
              <TaxLabel>特例申請</TaxLabel>
              <label className="flex items-center gap-2 p-3 border-2 rounded-xl dark:border-slate-600 cursor-pointer">
                <input
                  type="checkbox"
                  className="w-5 h-5 accent-pink-600"
                  checked={furusatoForm.isOneStop}
                  onChange={(e) =>
                    setFurusatoForm({ ...furusatoForm, isOneStop: e.target.checked })
                  }
                />
                <span className="text-sm font-bold dark:text-slate-300">利用する</span>
              </label>
            </div>
          </TaxForm>

          <TaxTable
            headers={["証明書", "寄付日", "自治体", "金額", "メモ", "特例"]}
            color="pink"
            rows={furusatoRecords.map((r) => ({
              id: r.id,
              cells: [
                <input
                  key={`check-${r.id}`}
                  type="checkbox"
                  checked={r.isReceived || false}
                  onChange={() => toggleFurusatoReceived(r.id)}
                  className="w-5 h-5 cursor-pointer accent-pink-600"
                />,
                r.date,
                r.city,
                `¥${r.amount.toLocaleString()}`,
                r.memo,
                r.isOneStop ? "適用" : "申告",
              ],
            }))}
            onDelete={(id) => setFurusatoRecords(furusatoRecords.filter((rec) => rec.id !== id))}
            emptyMessage="寄付の記録がありません"
            onSort={() => toggleSort("furusato")}
            sortOrder={sortOrder}
          />
        </div>
      )}
      {/* モーダルウィンドウ */}
      <EtaxModal
        isOpen={showEtaxModal}
        onClose={() => setShowEtaxModal(false)}
        summary={etaxSummary}
      />
      {/* 後略 */}

      <TrashModal
        isOpen={showTrashModal}
        onClose={() => setShowTrashModal(false)}
        deletedRecords={deletedRecords} // これは Hooks から受け取っている変数
        onRestore={restoreRecord} // これは Hooks から受け取っている関数
        onClearAll={clearTrash} // ✅ setDeletedRecords([]) の代わりに clearTrash を使う
      />

      {/* パターンB: クイック元に戻す通知（トースト） */}
      <UndoToast
        show={showUndo}
        lastDeleted={lastDeleted}
        onRestore={restoreRecord}
        onClose={() => setShowUndo(false)}
      />
      {/* <button
        type="button"
        onClick={() => startEdit(records[0])}
        className="p-2 bg-blue-500 text-white rounded"
      >
        編集テスト
      </button> */}
    </main>
  );
}
