// biome-ignore assist/source/organizeImports: <AUTO-GENERATED>
import { useId, type FC } from "react";
import { registerLocale } from "react-datepicker"; // 追加
import { ja } from "date-fns/locale/ja"; // 追加
import "react-datepicker/dist/react-datepicker.css"; // 必要ならスタイルも
import type { MedicalRecord, MedicalCategory, History } from "@/types/tax";

// コンポーネントの外で1回だけ実行されるように配置
registerLocale("ja", ja);

interface MedicalFormProps {
  onSubmit: (e: React.FormEvent) => void;
  formData: Omit<MedicalRecord, "id">;
  setFormData: (data: any) => void;
  history: History;
  editingId: string | null;
  onCancelEdit: () => void;
}

// 選択肢の定義
const CATEGORIES: MedicalCategory[] = ["診療代", "薬代", "交通費", "その他"];

export const MedicalForm: FC<MedicalFormProps> = ({
  onSubmit,
  formData,
  setFormData,
  history,
  editingId,
  onCancelEdit,
}) => {
  // すべての入力項目とリスト用に一意のIDを生成
  const dateId = useId();
  const patientId = useId();
  const patientListId = useId();
  const providerId = useId();
  const providerListId = useId();
  const categoryId = useId();
  const amountId = useId();
  const reimbursementId = useId();

  return (
    <form
      onSubmit={onSubmit}
      className="bg-white dark:bg-slate-800 p-8 rounded-3xl shadow-xl border border-slate-100 dark:border-slate-700 mb-12 animate-in fade-in slide-in-from-top-4 duration-500"
    >
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {/* 日付 */}
        <div className="space-y-2">
          <label
            htmlFor={dateId}
            className="text-xs font-black text-slate-500 dark:text-slate-400 ml-1 tracking-widest uppercase"
          >
            受診日
          </label>
          <input
            type={dateId}
            required
            value={formData.date}
            onChange={(e) => setFormData({ ...formData, date: e.target.value })}
            className="w-full p-4 rounded-2xl bg-slate-50 dark:bg-slate-900 border-2 border-transparent focus:border-blue-500 focus:bg-white dark:focus:bg-slate-800 outline-none transition-all font-bold text-slate-700 dark:text-slate-200"
          />
        </div>

        {/* 氏名（サジェスト付き） */}
        <div className="space-y-2">
          <label
            htmlFor={patientId}
            className="text-xs font-black text-slate-500 dark:text-slate-400 ml-1 tracking-widest uppercase"
          >
            氏名
          </label>
          <input
            type="text"
            required
            list={patientListId}
            placeholder="受診した人の名前"
            value={formData.patientName}
            onChange={(e) => setFormData({ ...formData, patientName: e.target.value })}
            className="w-full p-4 rounded-2xl bg-slate-50 dark:bg-slate-900 border-2 border-transparent focus:border-blue-500 focus:bg-white dark:focus:bg-slate-800 outline-none transition-all font-bold text-slate-700 dark:text-slate-200"
          />
          <datalist id={patientListId}>
            {history.patientNames.map((name) => (
              <option key={name} value={name} />
            ))}
          </datalist>
        </div>

        {/* 病院名・薬局名（サジェスト付き） */}
        <div className="space-y-2">
          <label
            htmlFor={providerId}
            className="text-xs font-black text-slate-500 dark:text-slate-400 ml-1 tracking-widest uppercase"
          >
            病院・薬局
          </label>
          <input
            id={providerId}
            type="text"
            required
            list={providerListId}
            placeholder="〇〇クリニック"
            value={formData.providerName}
            onChange={(e) => setFormData({ ...formData, providerName: e.target.value })}
            className="w-full p-4 rounded-2xl bg-slate-50 dark:bg-slate-900 border-2 border-transparent focus:border-blue-500 focus:bg-white dark:focus:bg-slate-800 outline-none transition-all font-bold text-slate-700 dark:text-slate-200"
          />
          <datalist id={providerListId}>
            {history.providerNames.map((p) => (
              <option key={p} value={p} />
            ))}
          </datalist>
        </div>

        {/* 区分（カテゴリ） */}
        <div className="space-y-2">
          <label
            htmlFor={categoryId}
            className="text-xs font-black text-slate-500 dark:text-slate-400 ml-1 tracking-widest uppercase"
          >
            区分
          </label>
          <select
            id={categoryId}
            value={formData.category} // tax.ts の MedicalRecord に category がある前提
            onChange={(e) =>
              setFormData({ ...formData, category: e.target.value as MedicalCategory })
            }
            className="w-full p-4 rounded-2xl bg-slate-50 dark:bg-slate-900 border-2 border-transparent focus:border-blue-500 focus:bg-white dark:focus:bg-slate-800 outline-none transition-all font-bold text-slate-700 dark:text-slate-200 appearance-none"
          >
            {CATEGORIES.map((cat) => (
              <option key={cat} value={cat}>
                {cat}
              </option>
            ))}
          </select>
        </div>

        {/* 支払金額 */}
        <div className="space-y-2">
          <label
            htmlFor={amountId}
            className="text-xs font-black text-slate-500 dark:text-slate-400 ml-1 tracking-widest uppercase"
          >
            支払金額
          </label>
          <div className="relative">
            <span className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400 font-bold">
              ¥
            </span>
            <input
              id={amountId}
              type="number"
              required
              min="0"
              value={formData.amount || ""}
              onChange={(e) => setFormData({ ...formData, amount: Number(e.target.value) })}
              className="w-full p-4 pl-10 rounded-2xl bg-slate-50 dark:bg-slate-900 border-2 border-transparent focus:border-blue-500 focus:bg-white dark:focus:bg-slate-800 outline-none transition-all font-bold text-slate-700 dark:text-slate-200"
            />
          </div>
        </div>

        {/* 補填額 */}
        <div className="space-y-2">
          <label
            htmlFor={reimbursementId}
            className="text-xs font-black text-slate-500 dark:text-slate-400 ml-1 tracking-widest uppercase"
          >
            保険等の補填額
          </label>
          <div className="relative">
            <span className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400 font-bold">
              ¥
            </span>
            <input
              id={reimbursementId}
              type="number"
              min="0"
              value={formData.reimbursement || ""}
              onChange={(e) => setFormData({ ...formData, reimbursement: Number(e.target.value) })}
              className="w-full p-4 pl-10 rounded-2xl bg-slate-50 dark:bg-slate-900 border-2 border-transparent focus:border-blue-500 focus:bg-white dark:focus:bg-slate-800 outline-none transition-all font-bold text-slate-700 dark:text-slate-200"
            />
          </div>
        </div>
      </div>

      <div className="mt-8 flex gap-4">
        <button
          type="submit"
          className={`flex-1 p-5 rounded-2xl font-black text-lg shadow-lg transition-all active:scale-95 ${
            editingId
              ? "bg-amber-500 hover:bg-amber-600 text-white"
              : "bg-blue-600 hover:bg-blue-700 text-white"
          }`}
        >
          {editingId ? "✨ 記録を更新する" : "➕ 記録を追加する"}
        </button>

        {editingId && (
          <button
            type="button"
            onClick={onCancelEdit}
            className="px-8 py-5 bg-slate-100 dark:bg-slate-700 text-slate-600 dark:text-slate-300 rounded-2xl font-black hover:bg-slate-200 transition-all"
          >
            キャンセル
          </button>
        )}
      </div>
    </form>
  );
};
