// biome-ignore assist/source/organizeImports: <AUTO-GENERATED>
import type { FC } from "react";
import { TaxTable } from "../../../components/TaxTable"; // 既存のTaxTableのパスに合わせて調整してください
import type { MedicalRecord } from "@/types/tax";

interface MedicalListProps {
  records: MedicalRecord[];
  sortOrder: "asc" | "desc";
  onSort: () => void;
  onEdit: (record: MedicalRecord) => void;
  onDelete: (id: string) => void;
}

export const MedicalList: FC<MedicalListProps> = ({
  records,
  sortOrder,
  onSort,
  onEdit,
  onDelete,
}) => {
  return (
    <div className="lg:col-span-2 flex flex-col gap-4">
      <h3 className="font-bold flex items-center gap-2 text-blue-600">📋 入力明細</h3>

      <TaxTable
        headers={["日付", "氏名", "場所", "金額"]}
        color="blue"
        rows={records.map((r) => ({
          id: r.id,
          cells: [
            r.date,
            r.patientName,
            r.providerName,
            `¥${r.amount.toLocaleString()}`,
            <div key={`actions-${r.id}`} className="flex gap-2">
              <button
                type="button"
                onClick={() => onEdit(r)}
                className="p-2 text-blue-600 hover:bg-blue-50 dark:hover:bg-blue-900/30 rounded-lg transition"
                title="編集"
              >
                ✏️
              </button>
            </div>,
          ],
        }))}
        onDelete={onDelete}
        emptyMessage="医療費のデータがありません"
        sortOrder={sortOrder}
        onSort={onSort}
      />
    </div>
  );
};
